export const en = {
  brand: "Sound Spa 2", localPrototype: "Local prototype", testMode: "Test mode", nowSelected: "Now selected",
  musicChannels: "Music channels", channels: "channels", ambient: "Ambient", previous: "Previous", next: "Next",
  standard: "Standard", shuffle: "Shuffle", repeatOne: "Repeat one", playing: "Playing", buffering: "Buffering", paused: "Paused", ready: "Ready",
  playingTrack: "Playing track", playbackError: "Playback error", readyToPlay: "Ready to play", plannedChannel: "Planned channel", locked: "Locked",
  noChannels: "No channels currently available", noPlayableChannels: "There are no playable music channels for this location.", playPause: "Play / Pause",
  previousTrack: "Previous track", nextTrack: "Next track", playbackMode: "Playback mode", ambientVolume: "Ambient volume",
  loadingCatalog: "Loading catalog", deviceSetupRequired: "Device setup required", unauthorizedDevice: "This player is not authorized for a V2 device.",
  catalogUnavailable: "Catalog unavailable", unableToLoadCatalog: "Unable to load the customer catalog.", player: "Player", prototypeAccess: "Prototype access", noAccount: "Local test · no account required",
  language: "Language", selectLanguage: "Select language", english: "English", russian: "Русский", vietnamese: "Tiếng Việt", thai: "ไทย",
  authSignupTitle: "Create your SoundSpa account", authSignupDescription: "Enter your email. We will send a secure verification link.", authEmail: "Email address", authSendVerification: "Send verification link", authSending: "Sending…", authEmailSent: "If the address can be used, we sent a secure link.", authLoginTitle: "Sign in to SoundSpa", authLoginDescription: "Enter your email to receive a secure sign-in link.", authRequestLogin: "Send sign-in link", authContinueTitle: "Continue to SoundSpa", authLinkConfirmation: "Your secure link is ready. Continue to verify your email or sign in.", authContinue: "Continue", authInvalidLink: "This link is invalid or expired. Request a new one.", authInvalidEmail: "Enter a valid email address.", authAccountTitle: "Your account", authEmailVerified: "Verified email", authLogout: "Sign out", authNoOrganization: "Account setup is not complete yet.", authSignInRequired: "Sign in to view your account.", authPartnerUnavailable: "This partner signup link is unavailable. Ask the partner for a new link.", authSignupLink: "Create an account", authLoginLink: "Already have an account? Sign in",
} as const;
