export const en = {
  brand: "Sound Spa 2", localPrototype: "Local prototype", testMode: "Test mode", nowSelected: "Now selected",
  musicChannels: "Music channels", channels: "channels", ambient: "Ambient", previous: "Previous", next: "Next",
  standard: "Standard", shuffle: "Shuffle", repeatOne: "Repeat one", playing: "Playing", buffering: "Buffering", paused: "Paused", ready: "Ready",
  playingTrack: "Playing track", playbackError: "Playback error", readyToPlay: "Ready to play", plannedChannel: "Planned channel", locked: "Locked",
  noChannels: "No channels currently available", noPlayableChannels: "There are no playable music channels for this location.", playPause: "Play / Pause",
  previousTrack: "Previous track", nextTrack: "Next track", playbackMode: "Playback mode", ambientVolume: "Ambient volume",
  loadingCatalog: "Loading catalog", deviceSetupRequired: "Device setup required", unauthorizedDevice: "This player is not authorized for a V2 device.",
  catalogUnavailable: "Catalog unavailable", unableToLoadCatalog: "Unable to load the customer catalog.", player: "Player", prototypeAccess: "Prototype access", noAccount: "Local test · no account required",
  language: "Language", selectLanguage: "Select language", english: "English", russian: "Русский", vietnamese: "Tiếng Việt", thai: "ไทย",
  authSignupTitle: "Create your SoundSpa account", authSignupDescription: "Enter your email. We will send a secure verification link.", authEmail: "Email address", authSendVerification: "Send verification link", authSending: "Sending…", authEmailSent: "If the address can be used, we sent a secure link.", authLoginTitle: "Sign in to SoundSpa", authLoginDescription: "Enter your email to receive a secure sign-in link.", authRequestLogin: "Send sign-in link", authContinueTitle: "Continue to SoundSpa", authLinkConfirmation: "Your secure link is ready. Continue to verify your email or sign in.", authContinue: "Continue", authInvalidLink: "This link is invalid or expired. Request a new one.", authInvalidEmail: "Enter a valid email address.", authAccountTitle: "Your account", authEmailVerified: "Verified email", authLogout: "Sign out", authNoOrganization: "Account setup is not complete yet.", authSignInRequired: "Sign in to view your account.", authPartnerUnavailable: "This partner signup link is unavailable. Ask the partner for a new link.", authSignupLink: "Create an account", authLoginLink: "Already have an account? Sign in",
  onboardingTitle: 'Set up your SoundSpa account', onboardingDescription: 'Add your business and first location to continue.', organizationName: 'Business name', locationName: 'First location name', timezone: 'Location time zone', timezoneHelp: 'Your device time zone is suggested when available. If it is missing, enter an IANA time zone such as Asia/Ho_Chi_Minh.', onboardingSubmit: 'Complete setup', onboardingSubmitting: 'Creating your account…', onboardingIncomplete: 'Account setup is not complete yet.', onboardingCompleted: 'Your account is ready.', onboardingInvalid: 'Check the business, location, and time zone details.', onboardingUnavailable: 'We could not complete setup. Please try again.', onboardingPartnerContext: 'This account started from a partner invitation. Continue using that partner invitation flow; ordinary setup is not available here.', trialLabel: 'SoundSpa Basic trial', trialDays: '{{days}} days remaining', trialLessThanDay: 'Less than one day remaining', trialEnded: 'Trial ended', trialActive: 'Trial active', accountOrganization: 'Organization', accountLocation: 'Location', accountTimezone: 'Time zone', timezoneRequired: 'Enter a valid IANA time zone.'
,
  partnerInvitePending: 'Your partner invitation is ready. Complete your business and first-location details to continue.', partnerSetupCompleted: 'Your partner setup is complete.', partnerInviteUnavailable: 'This partner invitation is unavailable or expired. Ask the partner for a new invitation.', partnerInviteAmbiguous: 'More than one partner invitation is pending. Contact the partner for help before continuing.', existingOrganization: 'This account already belongs to an Organization. A partner invitation cannot be attached here.', partnerAccess: 'Partner access', noAvailableChannels: 'No channels are currently available for this Location.', partnerClaimFailure: 'We could not confirm partner setup. Refresh your account page or try again.', authCheckEmailTitle: 'Check your email', authCheckEmailDescription: 'If this address can be used, we sent a secure link to it. Follow the link to continue.', partnerAccessActive: 'Partner access is active.', trialDaysOne: '{{days}} day remaining', trialDaysFew: '{{days}} days remaining', trialDaysMany: '{{days}} days remaining', customerDevices: "Devices", deviceConnect: "Connect device", deviceNameLabel: "Device name", deviceCreateLink: "Create connection link", deviceLinkReady: "Your connection link is ready", deviceLinkInstruction: "Open this link on the device that will play SoundSpa.", deviceCopyLink: "Copy link", deviceLinkCopied: "Link copied", deviceActive: "Active", deviceAwaitingActivation: "Awaiting activation", deviceActivated: "Activated", deviceRevoked: "Revoked", deviceActivationExpired: "Activation link expired", deviceProvisioningFailed: "Could not create the device connection. Please try again.", deviceAuthRequired: "Sign in again to connect a device.", deviceEmailUnverified: "Verify your email before connecting a device.", deviceLocationUnavailable: "You do not have permission to connect a device to this Location.", deviceNameRequired: "Enter a device name (up to 120 characters).", deviceCreating: "Creating link…", deviceNoDevices: "No devices connected yet.", deviceNoAuthorizedLocations: "No Locations are available for device setup.", deviceUnnamed: "Unnamed device", deviceLinkExpires: "Link expires: {{date}}", deviceCopyFailed: "Could not copy the link. Select and copy it manually.", } as const;
