services:
  # ОСНОВНОЙ САЙТ (Next.js)
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://soundspa:QQyo7zDqJMukdveU3C1LuJPyCAdDehbU@postgres:5432/soundspa
    depends_on:
      - postgres
    command: npm run start
    deploy:
      resources:
        limits:
          memory: 1G # Сайт может быть тяжелым

  # ФОНОВЫЙ ПОМОЩНИК (Тот самый скрипт с cron)
  worker:
    build: .
    # Используем твой скрипт из package.json
    command: npm run worker 
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://soundspa:QQyo7zDqJMukdveU3C1LuJPyCAdDehbU@postgres:5432/soundspa
    depends_on:
      - postgres
      - app
    # МОНТИРУЕМ ПАПКИ: чтобы менять код воркера без rebuild
    volumes:
      - ./scripts:/app/scripts
      - ./lib:/app/lib
      - ./db:/app/db
    deploy:
      resources:
        limits:
          memory: 512M # Воркеру хватит полгигабайта

  # БАЗА ДАННЫХ
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: soundspa
      POSTGRES_PASSWORD: QQyo7zDqJMukdveU3C1LuJPyCAdDehbU 
      POSTGRES_DB: soundspa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: