module.exports = {
  apps: [{
    name: 'soundspa-app',
    script: '.next/standalone/server.js',
    args: '',
    cwd: '/opt/soundspa-app',
    exec_mode: 'fork',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    env: {
      NODE_ENV: 'production',
      PORT: 3000,
      DATABASE_URL: 'postgres://soundspa:QQyo7zDqJMukdveU3C1LuJPyCAdDehbU@127.0.0.1:5432/soundspa',
      SESSION_SECRET: 'Cceba57d85e3bf841c8d5f5b2fe35fb051966dfaa8048431fefef0d4a43fe08c7',
      AGENTMAIL_API_KEY: 'am_us_inbox_c455b73fbb9ea81d558866f8ed465b14f2849bac647d3e75dbcedd198bf839e7',
      AGENTMAIL_FROM: 'soundspa@agentmail.to',
      AGENTMAIL_BASE_URL: 'https://api.agentmail.to/v0/',
      NEXT_PUBLIC_APP_URL: 'https://soundspa.bodhemusic.com',
      SOUNDSPA_ADMIN_PASSWORD: '1080',
      NEXT_PUBLIC_SOUNDSPA_DEBUG_MAIN_STREAM_URL: 'https://radio.bodhemusic.com/listen/deep_relax/radio.mp3',
      NEXT_PUBLIC_SOUNDSPA_DEBUG_NOISE_STREAM_URL: '/noise/forest.mp3',
    },
    error_file: '/root/.pm2/logs/soundspa-app-error.log',
    out_file: '/root/.pm2/logs/soundspa-app-out.log',
    log_file: '/root/.pm2/logs/soundspa-app-combined.log',
    time: true,
    kill_timeout: 5000,
    listen_timeout: 5000,
  }],
};
