name: Deploy SoundSpa App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build check
        run: |
          echo "Код прошел проверку. Теперь выполни команды на сервере вручную или настрой SSH-деплой."