import { operatorAuthResponse, operatorAuthStatus, isSameOriginMutation } from "../../../../../lib/v2/adminOperator";
import { addBaseChannel, removeBaseChannel } from "../../../../../db/v2/queries/base";
import { disableLocationAdminGrant, upsertLocationAdminGrant } from "../../../../../db/v2/queries/adminGrants";
import { channels, locations } from "../../../../../db/v2/schema";
import { eq } from "drizzle-orm";
import { v2Db } from "../../../../../db/v2/client";
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const dynamic = "force-dynamic";
export async function POST(request: Request) { const status = operatorAuthStatus(request.headers.get("authorization")); if (status !== 200) return operatorAuthResponse(status); if (!isSameOriginMutation(request)) return new Response("Same-origin request required.", { status: 403 }); const form = await request.formData(); const operation = String(form.get("operation") ?? ""); const channelId = String(form.get("channelId") ?? ""); const locationId = String(form.get("locationId") ?? ""); if (!uuid.test(channelId) || (operation.includes("admin") && !uuid.test(locationId))) return new Response("Invalid target.", { status: 400 }); try { if (operation === "add-base") await addBaseChannel(channelId); else if (operation === "remove-base") await removeBaseChannel(channelId); else if (operation === "enable-admin") { const [location] = await v2Db.select({ id: locations.id }).from(locations).where(eq(locations.id, locationId)); const [channel] = await v2Db.select({ id: channels.id }).from(channels).where(eq(channels.id, channelId)); if (!location || !channel) return new Response("Target not found.", { status: 404 }); await upsertLocationAdminGrant({ locationId, channelId }); } else if (operation === "disable-admin") await disableLocationAdminGrant(locationId, channelId); else return new Response("Unknown operation.", { status: 400 }); return Response.redirect(new URL(`/admin${locationId ? `?location=${locationId}&` : "?"}message=Saved`, request.url), 303); } catch (error) { return new Response(error instanceof Error ? error.message : "Mutation failed.", { status: 400 }); } }
